# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ae6f193ff0b32734b9eba29053d5db94473c0886b3799aecb8df71b4be8ff679932f481ad58b7d416fd02fd3a3b03034c9f9bb3c06d6afcede7d56ddf39144b

test:
  secret_key_base: 4080ddb4a50142c8646c297d68476c52079623a383bbeec254d6a337e2857c7898d2a8e448cab0313a3e6febe0f68a4b85ea7eeed23ba71343b28407d3626a9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
